### ISSUE TITLE
Usb audio interface not recognised by bear

### ISSUE THREAD

**Issue by JelleBakker** [dsperados/bear-audio#15]
Hi,

I am using an external usb audio card with a raspberry pi.
https://www.amazon.com/Channel-External-Sound-Audio-Adapter/dp/B007HISGRW/ref=sr_1_3?ie=UTF8&qid=1382967519&sr=8-3&keywords=usb+sound+card

The audio card is not recognised by bear(when I ask for all the audio outputs). But when I enter aplay -L in the command line of the raspberry pi, I do see the audio card.
So, it is recognised by the raspberry pi, but not by bear.

Jelle

**Comment by stijnfrishert** [comment]
Hi Jelle,

Ciska gave us that exact same card yesterday to test with, but our Pi doesn't recognize it in the first place! Running `lsusb` with the card plugged or unplugged doesn't make a difference.

Did you install a driver or something?
What version of the Raspberry Pi are you running?

**Comment by JelleBakker** [comment]
I think I have a raspberry pi 2b and I didn't install a driver.
aplay -L showes me a list of all the audio devices including the audio card.
I'll be at HKU friday and I can come tomorrow if you need me(or my raspberry pi).

Ps. I also speak dutch, so if you also do, that would be easier for communication :).

**Comment by stijnfrishert** [comment]
We're at the HKU this week from mon-wed anyhow, and I could come to office on thursday and friday as well, so if you could drop by that'd be great!

(Let's stick to english for future reference for other users)

**Comment by JelleBakker** [comment]
Oke, tomorrow I am at HKU and probably wednesday also

**Comment by stijnfrishert** [comment]
Ok, we fixed a bug where devices that do both input *and* output weren't listed. Tested, and it works!

(Your Pi's waiting or you here.)
